/-
The periodic graph and conductances of `ucplanar.tex:360–369`.
The four nearest-neighbor edges are supplemented by diagonal jumps from vertices
whose coordinate sum is even.
-/
import LatticeProb.Site
import LatticeProb.Network.Basic

open scoped Classical

/-- The vector `(1,1)` in the shared square lattice. -/
def UCPlanar.diagonalStep : LatticeProb.Site 2 := fun _ => 1

/-- The directed edge list issued from an even vertex. -/
def UCPlanar.crossingRelation (x y : LatticeProb.Site 2) : Prop :=
  Even (x 0 + x 1) ∧
    (y = x - LatticeProb.unit 0 ∨ y = x - LatticeProb.unit 1 ∨
     y = x + LatticeProb.unit 0 ∨ y = x + LatticeProb.unit 1 ∨
     y = x + (2 : ℤ) • UCPlanar.diagonalStep ∨
     y = x - (2 : ℤ) • UCPlanar.diagonalStep ∨
     y = x + UCPlanar.diagonalStep ∨ y = x - UCPlanar.diagonalStep)

/-- The undirected graph generated by the edge list. -/
def UCPlanar.crossingGraph : SimpleGraph (LatticeProb.Site 2) :=
  SimpleGraph.fromRel UCPlanar.crossingRelation

/-- The contribution from one endpoint to the conductance of an edge.
Each diagonal edge receives half its conductance from each endpoint. -/
noncomputable def UCPlanar.crossingOutgoing (a b t d : ℝ)
    (x y : LatticeProb.Site 2) : ℝ :=
  if Even (x 0 + x 1) then
    if y = x - LatticeProb.unit 0 ∨ y = x - LatticeProb.unit 1 then a
    else if y = x + LatticeProb.unit 0 ∨ y = x + LatticeProb.unit 1 then b
    else if y = x + (2 : ℤ) • UCPlanar.diagonalStep ∨
      y = x - (2 : ℤ) • UCPlanar.diagonalStep then t / 2
    else if y = x + UCPlanar.diagonalStep ∨ y = x - UCPlanar.diagonalStep then d / 2
    else 0
  else 0

/-- The symmetric conductance with parameters `A₁,A₂,A₃,A₄`. -/
noncomputable def UCPlanar.crossingConductance (a b t d : ℝ)
    (x y : LatticeProb.Site 2) : ℝ :=
  UCPlanar.crossingOutgoing a b t d x y + UCPlanar.crossingOutgoing a b t d y x

/-- The diagonal function normalized to be one at the origin. -/
noncomputable def UCPlanar.diagonalFunction (a b : ℝ) (x : LatticeProb.Site 2) : ℝ :=
  if x 0 = x 1 then (-b / a) ^ (x 0) else 0
