"""Produce the Lean certificate: a machine-checked record of what is proved.

The certificate is not prose.  Every line of it is generated by running the
checkers and by asking Lean itself for each theorem's axiom closure, so a reader
can reproduce it with the commands it names and compare byte for byte.

    python3 tools/certificate.py            # write CERTIFICATE.md
    python3 tools/certificate.py --check    # verify the file on disk is current
"""

from __future__ import annotations

import hashlib
import os
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("certificate.py: PyYAML is required (pip install pyyaml)")

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "ledger" / "manifest.yaml"
OUT = ROOT / "CERTIFICATE.md"
ELAN = str(Path.home() / ".elan" / "bin")

# The three axioms of Lean's own logic.  Anything else in a closure -- above all
# `sorryAx` -- means the statement is not proved.
CLASSICAL = {"propext", "Classical.choice", "Quot.sound"}

# The cited inputs, and the theorem that consumes each one.  The certificate
# states the use site so that a reader can see which frozen statement carries
# the predicate as a hypothesis.
USE_SITES = {
    "X-001": "carried as a hypothesis by `N-008` and `N-001`; the periodic form is proved directly, so no proof invokes it",
    "X-002": "`N-003`, `N-002` and `N-001`",
    "X-003": "`N-003`, `N-002` and `N-001`",
    "X-005": "`N-006`, `N-008` and `N-001`",
    "X-007": "`N-007`, `N-006`, `N-008` and `N-001`",
}


def run(cmd: list[str], **kw) -> subprocess.CompletedProcess:
    env = {**os.environ, "PATH": ELAN + ":" + os.environ.get("PATH", "")}
    return subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, env=env, **kw)


def module_names() -> list[str]:
    names = []
    for f in sorted((ROOT / "UCPlanar").rglob("*.lean")):
        names.append(str(f.relative_to(ROOT).with_suffix("")).replace("/", "."))
    return names


def axiom_lines(exports: list[str]) -> dict[str, str]:
    """Ask Lean for each export's axiom closure, in one elaboration."""
    imports = sorted({f"import {m}" for m in module_names()})
    src = "\n".join(imports) + "\n" + "\n".join(f"#print axioms {e}" for e in exports) + "\n"
    probe = ROOT / "scratch" / "_certificate_probe.lean"
    probe.parent.mkdir(exist_ok=True)
    probe.write_text(src, encoding="utf-8")
    try:
        r = run(["lake", "env", "lean", str(probe)], timeout=3600)
    finally:
        probe.unlink(missing_ok=True)
    if r.returncode != 0:
        raise RuntimeError("axiom probe did not elaborate:\n" + r.stdout + r.stderr)
    out: dict[str, str] = {}
    for line in r.stdout.splitlines():
        m = re.match(r"'([^']+)' (?:depends on axioms: \[(.*)\]|does not depend on any axioms)", line)
        if m:
            out[m.group(1)] = m.group(2) or ""
    missing = sorted(set(exports) - out.keys())
    if missing:
        raise RuntimeError("missing axiom closures: " + ", ".join(missing))
    for name, axioms in out.items():
        extra = {a.strip() for a in axioms.split(",") if a.strip()} - CLASSICAL
        if extra:
            raise RuntimeError(f"{name}: nonclassical axioms {sorted(extra)}")
    return out


def frozen_hash(node: dict) -> str:
    text = (ROOT / node["file"]).read_text(encoding="utf-8")
    b = text[text.index("-- FROZEN-STATEMENT-BEGIN") + len("-- FROZEN-STATEMENT-BEGIN"):
             text.index("-- FROZEN-STATEMENT-END")]
    if b.startswith("\n"):
        b = b[1:]
    return hashlib.sha256(b.encode("utf-8")).hexdigest()


def paper_label(source: str) -> str:
    """The paper anchor: the label when the source names one, else the lines."""
    m = re.search(r"label ([A-Za-z][A-Za-z0-9:_-]*)", source)
    if m:
        return f"`{m.group(1)}`"
    m = re.search(r"\(([A-Za-z][A-Za-z0-9:_-]*)\)", source)
    if m:
        return f"`{m.group(1)}`"
    m = re.search(r"ucplanar\.tex:(\d+)-(\d+)", source)
    if m:
        return f"lines {m.group(1)}-{m.group(2)}"
    m = re.search(r"ucplanar\.tex:(\d+)", source)
    return f"line {m.group(1)}" if m else "—"


def build() -> str:
    manifest = yaml.safe_load(MANIFEST.read_text(encoding="utf-8"))
    nodes = manifest["nodes"]
    exports = [n["export"] for n in nodes]
    theorems = [n for n in nodes if n["kind"] == "theorem"]
    externals = [n for n in nodes if n["kind"] == "definition"]

    r = run(["lake", "build", "UCPlanar"], timeout=7200)
    jobs = re.search(r"Build completed successfully \((\d+) jobs\)", r.stdout)
    if r.returncode != 0:
        raise RuntimeError("certificate: Lean build failed\n" + r.stdout + r.stderr)
    for checker in ("check_manifest.py", "check_axioms.py", "check_constants.py",
                    "check_warnings.py", "sync_docs.py"):
        gate = run([sys.executable, "tools/" + checker], timeout=3600)
        if gate.returncode != 0:
            raise RuntimeError(f"certificate: {checker} failed\n" + gate.stdout + gate.stderr)
    warnings = [l for l in r.stdout.splitlines() if l.startswith("warning:")]
    if warnings:
        raise RuntimeError("certificate: unexpected build warnings")

    ax = axiom_lines(exports)
    sealed = sum(n["kind"] == "theorem" and n["state"] == "SEALED" for n in nodes)
    inputs = len(externals)
    toolchain = (ROOT / "lean-toolchain").read_text().strip()
    ml = re.search(r'"rev":\s*"([0-9a-f]{40})"',
                   (ROOT / "lake-manifest.json").read_text(encoding="utf-8"))
    paper = ROOT / "paper" / "ucplanar.tex"
    paper_sha = hashlib.sha256(paper.read_bytes()).hexdigest()

    lines: list[str] = []
    A = lines.append
    A("# Lean certificate")
    A("")
    A("*Unique continuation on planar graphs*, Bou-Rabee, Cooperman, Ganguly,")
    A("Discrete Analysis 2025:16.  This file records what a machine has checked,")
    A("and how to check it again.  It is generated by `python3 tools/certificate.py`;")
    A("do not edit it by hand.")
    A("")
    A("## What is claimed")
    A("")
    A("The paper's registered statements are proved in Lean 4 from Mathlib and the")
    A("shared library `LatticeProb`, under the hypotheses displayed in their frozen")
    A("declarations, with no added axiom and no `sorry`.")
    A("Cited inputs are proposition-valued predicates in `UCPlanar/External/`,")
    A("carried as explicit hypotheses together with each theorem's own hypotheses.")
    A("`CORRESPONDENCE.md` records the correspondence with the paper and")
    A("`PROOF.md` describes the proof and the Lean tree.")
    A("")
    A("## Environment")
    A("")
    A("| | |")
    A("|---|---|")
    A(f"| Lean toolchain | `{toolchain}` |")
    A(f"| Mathlib revision | `{ml.group(1) if ml else 'unknown'}` |")
    A(f"| Paper (`paper/ucplanar.tex`) SHA-256 | `{paper_sha}` |")
    A(f"| Build | succeeded{f', {jobs.group(1)} jobs' if jobs else ''} |")
    A(f"| Build warnings | {len(warnings)} |")
    A(f"| Generated | {date.today().isoformat()} |")
    A("")
    A("## Reproducing it")
    A("")
    A("```")
    A("elan toolchain install $(cat lean-toolchain)")
    A("lake exe cache get      # optional: prebuilt Mathlib")
    A("lake build UCPlanar")
    A("python3 tools/check_manifest.py     # frozen statements match their hashes")
    A("python3 tools/check_axioms.py       # no axiom closure contains sorryAx")
    A("python3 tools/check_warnings.py     # the build emits no unauthorized warning")
    A("python3 tools/check_constants.py    # parameter order for uniform constants")
    A("python3 tools/sync_docs.py --write  # generate the manifest-derived tables")
    A("python3 tools/certificate.py --check")
    A("```")
    A("")
    A("## The theorems, and what each depends on")
    A("")
    A("`#print axioms` reports the full transitive axiom closure of a proof.  A")
    A("closure of exactly `propext, Classical.choice, Quot.sound` is classical")
    A("mathematics and nothing more; those three are Lean's own, not ours.")
    A("`sorryAx` in a closure would mean the statement is not proved.  It appears")
    A("nowhere below.")
    A("")
    A("| # | node | Lean name | state | paper | axiom closure |")
    A("|---|---|---|---|---|---|")
    clean = 0
    for i, n in enumerate(nodes, 1):
        e = n["export"]
        got = {a.strip() for a in ax[e].split(",") if a.strip()}
        extra = got - CLASSICAL
        if n.get("kind") == "definition":
            verdict = "assumed (a cited theorem, stated as a proposition)"
        elif not extra:
            verdict = "classical only"
            clean += 1
        else:
            verdict = "**" + ", ".join(sorted(extra)) + "**"
        A(f"| {i} | `{n['id']}` | `{e}` | `{n['state']}` | {paper_label(n['source'])} | {verdict} |")
    A("")
    A(f"All {clean} theorem declarations have axiom closures contained in the three")
    A(f"classical axioms. The {sealed} theorem nodes are `SEALED`; the {inputs} external")
    A("definitions are `FROZEN`. A clean definition does not supply a proof of its")
    A("proposition.")
    A("")
    A("## External inputs")
    A("")
    A("Each external predicate is a cited theorem of the literature, stated in the")
    A("paper's vocabulary and carried as an explicit hypothesis.  The table records")
    A("the frozen statement that consumes it.")
    A("")
    A("| node | Lean name | consumed by |")
    A("|---|---|---|")
    for n in externals:
        A(f"| `{n['id']}` | `{n['export']}` | {USE_SITES.get(n['id'], '—')} |")
    A("")
    A("## Frozen statements")
    A("")
    A("The bytes of each statement are pinned, so a statement cannot be weakened")
    A("after the fact without the hash changing.  `tools/check_manifest.py`")
    A("verifies these; the recipe is in `CORRESPONDENCE.md`.")
    A("")
    A("| node | SHA-256 of the frozen statement |")
    A("|---|---|")
    for n in nodes:
        h = frozen_hash(n)
        flag = "" if h == n["frozen_sha256"] else "  ← MISMATCH"
        A(f"| `{n['id']}` | `{h}`{flag} |")
    A("")
    A("## What is not claimed")
    A("")
    A("- The cited theorems in `UCPlanar/External/` (the rows marked *assumed*")
    A("  above) are not proved here; each statement that uses one carries it as an")
    A("  explicit hypothesis.")
    A("- The counterexample of Section 5 is a statement about one family of")
    A("  conductances on the square lattice; nothing here bears on other graphs.")
    A("- The proof ideas and the related work of Section 1 are outside the")
    A("  formalization.")
    A("")
    return "\n".join(lines) + "\n"


def main() -> int:
    try:
        text = build()
    except (RuntimeError, subprocess.TimeoutExpired) as error:
        print(f"certificate: {error}", file=sys.stderr)
        return 1
    if "--check" in sys.argv[1:]:
        if not OUT.exists():
            print("certificate: CERTIFICATE.md is missing", file=sys.stderr)
            return 1
        cur = OUT.read_text(encoding="utf-8")
        strip = lambda s: re.sub(r"\| Generated \| .* \|", "", s)
        if strip(cur) != strip(text):
            print("certificate: CERTIFICATE.md is out of date; regenerate it",
                  file=sys.stderr)
            return 1
        print("certificate: OK (CERTIFICATE.md matches the checked state)")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"certificate: wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
