"""Regenerate the manifest-derived tables in README.md and CORRESPONDENCE.md.

Both documents restate what `ledger/manifest.yaml` already records: how many
nodes exist, what state each is in, and where in the paper each one comes from.
Restated facts go stale.  Everything between a BEGIN/END marker pair below is
generated from the manifest, so the prose in those files never disagrees with
the checker again.

    python3 tools/sync_docs.py            # check, exit 1 if a block is stale
    python3 tools/sync_docs.py --write    # regenerate the blocks in place
"""

from __future__ import annotations

import re
import sys
from collections import Counter
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("sync_docs.py: PyYAML is required (pip install pyyaml)")

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "ledger" / "manifest.yaml"

SURFACE_BEGIN = "<!-- FROZEN-SURFACE-BEGIN (generated by tools/sync_docs.py) -->"
SURFACE_END = "<!-- FROZEN-SURFACE-END -->"
STATUS_BEGIN = "<!-- STATUS-BEGIN (generated by tools/sync_docs.py) -->"
STATUS_END = "<!-- STATUS-END -->"

LABEL_RE = re.compile(r"label ([A-Za-z][A-Za-z0-9:_-]*)")
RANGE_RE = re.compile(r"ucplanar\.tex:\d+-\d+")


def paper_cell(source: str) -> str:
    """The `paper` column: line range plus label, or the guard's own wording."""
    rng = RANGE_RE.search(source)
    lab = LABEL_RE.search(source)
    if rng and lab:
        return f"`{rng.group(0)}`, `{lab.group(1)}`"
    return source


def surface_table(nodes: list[dict]) -> str:
    rows = ["| id | Lean | paper | state |", "|---|---|---|---|"]
    for n in nodes:
        rows.append(
            f"| `{n['id']}` | `{n['export']}` | {paper_cell(n['source'])} "
            f"| {n['state']} |")
    return "\n".join(rows)


def status_block(nodes: list[dict]) -> str:
    counts = Counter(n["state"] for n in nodes)
    parts = ", ".join(f"{counts[s]} `{s}`" for s in sorted(counts))
    draft = [n["id"] for n in nodes if n["state"] == "DRAFT_SORRY"]
    sealed = counts["SEALED"]
    if not nodes:
        body = "No declarations have been registered."
    else:
        body = (f"{sealed} theorem(s) are proved and machine-checked: no `sorry`, no "
                f"axiom added by this development, and an axiom closure of exactly "
                f"Lean's three standard axioms `propext`, `Classical.choice` and "
                f"`Quot.sound`.")
        if counts["FROZEN"]:
            body += (f" {counts['FROZEN']} result(s) are cited from the literature and "
                     f"stated as explicit hypotheses rather than proved here, so the theorems "
                     f"that use them are proved conditional on them.")
        if draft:
            body += " Still open: " + ", ".join(f"`{i}`" for i in draft) + "."
    detail = f" — {parts}" if parts else ""
    return (
        f"Status: **{len(nodes)} registered nodes{detail}.** {body}\n\n"
        "Counts are generated from `ledger/manifest.yaml` by\n"
        "`python3 tools/sync_docs.py`. Run `python3 tools/check_axioms.py`\n"
        "to check registered axiom closures.")


def splice(text: str, begin: str, end: str, body: str) -> str:
    i, j = text.find(begin), text.find(end)
    if i < 0 or j < 0:
        raise LookupError(f"missing marker pair {begin!r}")
    return text[:i] + begin + "\n\n" + body + "\n\n" + text[j:]


def main() -> int:
    write = "--write" in sys.argv[1:]
    nodes = (yaml.safe_load(MANIFEST.read_text(encoding="utf-8")) or {}).get("nodes") or []

    targets = [
        (ROOT / "CORRESPONDENCE.md", SURFACE_BEGIN, SURFACE_END, surface_table(nodes)),
        (ROOT / "README.md", STATUS_BEGIN, STATUS_END, status_block(nodes)),
    ]

    stale = []
    for path, begin, end, body in targets:
        text = path.read_text(encoding="utf-8")
        try:
            want = splice(text, begin, end, body)
        except LookupError as exc:
            print(f"sync_docs: {path.name}: {exc}", file=sys.stderr)
            return 2
        if want != text:
            stale.append((path, want))

    if not stale:
        print(f"sync_docs: OK ({len(nodes)} nodes; README.md and "
              f"CORRESPONDENCE.md agree with the manifest)")
        return 0

    for path, want in stale:
        print(f"  stale: {path.relative_to(ROOT)}")
        if write:
            path.write_text(want, encoding="utf-8")

    if not write:
        print("\nsync_docs: rerun with --write to regenerate", file=sys.stderr)
        return 1
    print(f"\nsync_docs: regenerated {len(stale)} block(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
